name: CI/CD - Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU (for cross-build)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ secrets.KUBE_CONFIG_DATA != '' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.30.0'    # pick a kubectl version appropriate for your cluster

    - name: Setup Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config view
      shell: bash

    - name: Update image in k8s Deployment
      env:
        IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:${{ github.sha }}
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f k8s/namespace.yaml
        # replace image in deployment (patch)
        kubectl apply -f k8s/service.yaml -n wisecow || true
        kubectl apply -f k8s/ingress.yaml -n wisecow || true
        # create deployment from file but patch image if already exists:
        if kubectl -n wisecow get deploy wisecow-deployment >/dev/null 2>&1; then
          kubectl -n wisecow set image deployment/wisecow-deployment wisecow=${IMAGE}
        else
          # update deployment manifest image to the built image:
          sed "s|DOCKERHUB_USERNAME/wisecow:latest|${IMAGE}|g" k8s/deployment.yaml | kubectl apply -f -
        fi
